
version: '3.3'

volumes:
  logstash-data:
  package-data:

services:

  elasticsearch:
    build: ./elasticsearch
    image: "rhub/search-elasticsearch:0.0.3"
    environment:
    - cluster.name=search-cluster
    - bootstrap.memory_lock=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - package-data:/usr/share/elasticsearch/data
    deploy:
      restart_policy:
        delay: 5s
        window: 30s

  elastic-seed:
    build: ./seed
    image: "rhub/search-seed:0.0.3"
    depends_on:
    - elasticsearch
    entrypoint:
    - bash
    - -c
    - /seed/elastic.sh
    deploy:
      restart_policy:
        condition: on-failure

  logstash:
    build: ./logstash
    image: "rhub/search-logstash:0.0.3"
    volumes:
    - logstash-data:/usr/share/logstash/data
    depends_on:
    - elasticsearch
    - elastic-seed
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        window: 30s

  nginx:
    build: ./nginx
    image: "rhub/search-nginx:0.0.3"
    ports:
    - "80:80"
    depends_on:
    - elasticsearch
    entrypoint:
    - sh
    - -c
    - /entrypoint.sh
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        window: 10s

  cron:
    build: ./cron
    image: "rhub/search-cron:0.0.3"
    depends_on:
    - elasticsearch
    deploy:
      restart_policy:
        condition: any
