version: '3.3'

volumes:
  package-data:
  logstash-data:

services:

  elasticsearch:
    image: "elasticsearch:7.17.10"
    environment:
    - discovery.type=single-node
    - cluster.name=search-cluster
    - bootstrap.memory_lock=false
    ports:
    - "9200:9200"
    - "9300:9300"
    volumes:
    - package-data:/usr/share/elasticsearch/data
    - ./elastic/synonyms.txt:/usr/share/elasticsearch/config/synonyms.txt
    networks:
      default:
        aliases:
        - dokku-elasticsearch-cran

  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
    - "3000:80"
    command: nodemon bin/www.js
    volumes:
    - ./app:/src
    environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200

  logstash:
    build:
      context: .
      dockerfile: ./logstash/Dockerfile
    volumes:
    - logstash-data:/usr/share/logstash/data
